drop index U_FACT_STAR.IDX_PROD;
drop table U_FACT_STAR.DIM_TYPE_PRODUCT_SCD cascade constraints;
drop table U_FACT_STAR.DIM_FACTORY cascade constraints;
drop table U_FACT_STAR.DIM_GEO_LOCATIONS cascade constraints;
drop index U_FACT_STAR.I_DEPT_NAME;

drop table U_FACT_STAR.DIM_DEPT cascade constraints;
alter table U_FACT_STAR.DIM_WORKER_SCD
    drop constraint FK_DIM_WORK_REFERENCE_DIM_DEPT;

drop index U_FACT_STAR.IDX_WORKER;

drop table U_FACT_STAR.DIM_WORKER_SCD cascade constraints;

/*==============================================================*/
/* Table: DIM_WORKER_SCD                                        */
/*==============================================================*/
create table U_FACT_STAR.DIM_WORKER_SCD
(
    wk_id      NUMBER(22, 0) not null,
    dept_id    NUMBER(22, 0),
    name       VARCHAR(50),
    salary     INT,
    valid_from DATE          not null,
    valid_to   DATE,
    is_active  VARCHAR2(4),
    insert_dt  DATE,
    constraint PK_DIM_WORKER_SCD primary key (wk_id, valid_from)
);
/*==============================================================*/
/* Index: IDX_WORKER                                            */
/*==============================================================*/
create index U_FACT_STAR.IDX_WORKER on U_FACT_STAR.DIM_WORKER_SCD (
                                                                   wk_id ASC,
                                                                   is_active ASC,
                                                                   valid_from ASC
    );

alter table U_FACT_STAR.DIM_WORKER_SCD
    add constraint FK_DIM_WORK_REFERENCE_DIM_DEPT foreign key (dept_id)
        references U_FACT_STAR.DIM_DEPT (dept_id);



/*==============================================================*/
/* Table: DIM_DEPT                                              */
/*==============================================================*/
create table U_FACT_STAR.DIM_DEPT
(
    dept_id   NUMBER(22, 0) GENERATED by default on null as IDENTITY,
    name      VARCHAR(50),
    mng_id    NUMBER(22, 0),
    insert_dt DATE,
    update_dt DATE,
    fact_id   NUMBER(22, 0),
    constraint PK_DIM_DEPT primary key (dept_id)
);

/*==============================================================*/
/* Index: I_DEPT_NAME                                           */
/*==============================================================*/
create unique index U_FACT_STAR.I_DEPT_NAME on U_FACT_STAR.DIM_DEPT (
                                                                     name ASC
    );


/*==============================================================*/
/* Table: DIM_GEO_LOCATIONS                                     */
/*==============================================================*/
-- create table U_FACT_STAR.DIM_GEO_LOCATIONS
-- (
--     loc_id     NUMBER(22, 0) GENERATED by default on null as IDENTITY,
--     COUNTRY_ID NUMBER(22, 0),
--     STATE_ID   NUMBER(22, 0),
--     CITY_ID    NUMBER(22, 0),
--     constraint PK_DIM_GEO_LOCATIONS primary key (loc_id)
-- );

create table U_FACT_STAR.DIM_GEO_LOCATIONS
(
    loc_id  NUMBER(22, 0) GENERATED by default on null as IDENTITY,
    COUNTRY VARCHAR(100),
    STATE   VARCHAR(100),
    CITY    VARCHAR(100),
    constraint PK_DIM_GEO_LOCATIONS primary key (loc_id)
);


-- /*==============================================================*/
-- /* Table: DIM_CITY                                              */
-- /*==============================================================*/
-- create table U_FACT_STAR.DIM_CITY
-- (
--     ID   NUMBER(22, 0) GENERATED by default on null as IDENTITY,
--     NAME VARCHAR(100),
--     constraint PK_DIM_CITY primary key (ID)
-- );
--
-- /*==============================================================*/
-- /* Table: DIM_STATE                                             */
-- /*==============================================================*/
-- create table U_FACT_STAR.DIM_STATE
-- (
--     ID   NUMBER(22, 0) GENERATED by default on null as IDENTITY,
--     NAME VARCHAR(100),
--     constraint PK_DIM_STATE primary key (ID)
-- );
--
-- /*==============================================================*/
-- /* Table: DIM_COUNTRY                                           */
-- /*==============================================================*/
-- create table U_FACT_STAR.DIM_COUNTRY
-- (
--     ID   NUMBER(22, 0) GENERATED by default on null as IDENTITY,
--     NAME VARCHAR(100),
--     constraint PK_DIM_COUNTRY primary key (ID)
-- );


/*==============================================================*/
/* Table: DIM_FACTORY                                           */
/*==============================================================*/
create table U_FACT_STAR.DIM_FACTORY
(
    fact_id   NUMBER(22, 0) not null,
    name      VARCHAR(50),
    insert_dt DATE,
    update_dt DATE,
    loc_id    NUMBER(22, 0),
    constraint PK_DIM_FACTORY primary key (fact_id)
);

/*==============================================================*/
/* Table: DIM_TYPE_PRODUCT_SCD                                  */
/*==============================================================*/
create table U_FACT_STAR.DIM_TYPE_PRODUCT_SCD
(
    pr_t_id    NUMBER(22, 0),
    name       VARCHAR(50),
    meta       VARCHAR(200),
    sale_price NUMBER(20),
    valid_from DATE,
    valid_to   DATE,
    is_active  VARCHAR2(4),
    insert_dt  DATE
);

/*==============================================================*/
/* Index: IDX_PROD                                              */
/*==============================================================*/
create index U_FACT_STAR.IDX_PROD on U_FACT_STAR.DIM_TYPE_PRODUCT_SCD (
                                                                       insert_dt ASC,
                                                                       valid_from ASC,
                                                                       is_active ASC
    );

grant select, insert, update, delete on U_FACT_STAR.DIM_TYPE_PRODUCT_SCD to U_FACT_CLS;
grant select, insert, update, delete on U_FACT_STAR.DIM_FACTORY to U_FACT_CLS;
grant select, insert, update, delete on U_FACT_STAR.DIM_GEO_LOCATIONS to U_FACT_CLS;
grant select, insert, update, delete on U_FACT_STAR.DIM_DEPT to U_FACT_CLS;
grant select, insert, update, delete on U_FACT_STAR.DIM_WORKER_SCD to U_FACT_CLS;

COMMIT;