TRUNCATE TABLE U_FACT_STAR.DIM_TYPE_PRODUCT_SCD;
TRUNCATE TABLE U_FACT_STAR.DIM_FACTORY;
TRUNCATE TABLE U_FACT_STAR.DIM_DEPT;
TRUNCATE TABLE U_FACT_STAR.DIM_GEO_LOCATIONS;
TRUNCATE TABLE U_FACT_STAR.DIM_WORKER_SCD;

COMMIT;