insert into u_f_dw_ext_references.SA_FACTORY(fact_id, name, county, state, city)
      values(0, 'VOLKSWAGEN AG - Wolfsburg', 'Germary', 'niedersachsen', 'Wolfsburg')
insert into u_f_dw_ext_references.SA_FACTORY(fact_id, name, county, state, city)
      values(1, 'VOLKSWAGEN AG - Emden A', 'Germary', 'niedersachsen', 'Emden')
insert into u_f_dw_ext_references.SA_FACTORY(fact_id, name, county, state, city)
      values(2, 'VOLKSWAGEN AG - Emden B', 'Germary', 'niedersachsen', 'Emden')
insert into u_f_dw_ext_references.SA_FACTORY(fact_id, name, county, state, city)
      values(3, 'VOLKSWAGEN AG - Hanover', 'Germary', 'Hanover', 'Wolfsburg')